tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "osx-cross/avr"
brew "avrdude"
brew "cocoapods"
brew "ffmpeg"
brew "fzf"
brew "gibo"
brew "git"
brew "htop"
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "ios-deploy"
brew "libusbmuxd", args: ["HEAD"]
brew "mas"
brew "mecab"
brew "mono"
brew "nkf"
brew "nmap"
brew "nodenv"
brew "osslsigncode"
brew "p7zip"
brew "pwgen"
brew "redis"
brew "snapcraft"
brew "tmux"
brew "tree"
brew "wget"
brew "yarn"
brew "zsh"
brew "osx-cross/avr/avr-gcc"
cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "multipass"
cask "slack"
cask "visual-studio-code"
mas "Xcode", id: 497799835

