tap "buildpacks/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "arp-scan"
brew "coreutils"
brew "asdf"
brew "python@3.9"
brew "unbound"
brew "cask"
brew "cocoapods"
brew "docker"
brew "gobject-introspection"
brew "harfbuzz"
brew "libass"
brew "srt"
brew "ffmpeg"
brew "fzf"
brew "gibo"
brew "git"
brew "git-secrets"
brew "go"
brew "grep"
brew "htop"
brew "libusbmuxd"
brew "libimobiledevice"
brew "ideviceinstaller"
brew "imagemagick"
brew "ios-deploy"
brew "jq"
brew "libgsf"
brew "libxml2"
brew "mas"
brew "maven"
brew "mecab"
brew "nkf"
brew "nmap"
brew "node-build"
brew "nodenv"
brew "osslsigncode"
brew "p7zip"
brew "postgresql"
brew "pstree"
brew "pwgen"
brew "python@3.8"
brew "redis"
brew "snapcraft"
brew "terraform", link: false
brew "terraformer"
brew "tfenv"
brew "tflint"
brew "tmux"
brew "tnftp"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "buildpacks/tap/pack"
brew "heroku/brew/heroku"
cask "anaconda"
cask "corretto11"
cask "cyberduck"
cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "intellij-idea-ce"
cask "iterm2"
cask "multipass"
cask "slack"
cask "starleaf"
cask "visual-studio-code"
cask "zoom"
mas "Apple Configurator 2", id: 1037126344
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
